# Generated by Django 2.2 on 2019-12-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='todotask',
            index_together={('project', 'tag', 'taskPriority', 'deadline', 'done')},
        ),
    ]
